### ISSUE TITLE
Can this work Server Side only? It's really important for my server

### ISSUE THREAD

**Issue by echoless3484** [Yeleefff/affordable#1]
Can this work Server Side only? It's really important for my server

**Comment by Yeleefff** [comment]
With the current implementation it is required both server side and client side. There may be a way to potentially do the logic server side, however, screen logic is generally a client side thing so for the screen to actually show that an item is enchantable and not over the level limit it would have to be installed client side as well.

**Comment by echoless3484** [comment]
That makes sense, thank you for the response!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
